language: go

go:
- 1.9.1

sudo: required
dist: trusty

go_import_path: github.com/honeytrap/honeytrap-agent

services:
 - docker

os:
- linux

env:
- ARCH=x86_64

addons:
  apt:
    packages:
    - lxc

install:
  - sudo apt-get install -y software-properties-common python-software-properties
  - sudo apt-get update -qq
  - go get -u -v github.com/alecthomas/gometalinter
  - go get -u -v github.com/honeytrap/honeytrap-agent
  - gometalinter --install

script:
  # - gometalinter --deadline 2m --errors --vendor ./...
  - go test -v ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go build ./...
  - GOOS=linux GOARCH=arm go build ./...
  - GOOS=darwin GOARCH=amd64 go build ./...

after_success:
- bash <(curl -s https://codecov.io/bash)
